sudo: required

language: go

go:
  - 1.6

services:
  - docker

before_install:
  - docker build -t hvnsweeting/saltstack_ubuntu .
  - docker ps -a

script:
  - docker run carlad/sinatra /bin/sh -c "salt-call -c /root/salt/states/test state.sls vim.test"
