sudo: required

language: python

go:
  - 2.7

services:
  - docker

before_install:
  - docker build -t hvnsweeting/saltstack_ubuntu .
  - docker ps -a

install: true

script:
  - docker run hvnsweeting/saltstack_ubuntu -v runner.py:/app/runner.py runner.py
